opt -da -analyze box_algebra.bc
opt -da -analyze box_alloc.bc
opt -da -analyze box.bc
opt -da -analyze box_neighbors.bc
opt -da -analyze coarsen.bc
opt -da -analyze communication.bc 
opt -da -analyze communication_info.bc
opt -da -analyze computation.bc
opt -da -analyze cyclic_reduction.bc
opt -da -analyze general.bc
opt -da -analyze grow.bc
opt -da -analyze HYPRE_pcg.bc
opt -da -analyze HYPRE_struct_grid.bc
opt -da -analyze HYPRE_struct_matrix.bc
opt -da -analyze HYPRE_struct_pcg.bc
opt -da -analyze HYPRE_struct_smg.bc
opt -da -analyze HYPRE_struct_stencil.bc
opt -da -analyze HYPRE_struct_vector.bc
opt -da -analyze memory.bc
opt -da -analyze mpistubs.bc
opt -da -analyze pcg.bc
opt -da -analyze pcg_struct.bc
opt -da -analyze point_relax.bc
opt -da -analyze project.bc
opt -da -analyze random.bc
opt -da -analyze semi_interp.bc
opt -da -analyze semi_restrict.bc
opt -da -analyze smg2000.bc
opt -da -analyze smg2_setup_rap.bc
opt -da -analyze smg3_setup_rap.bc
opt -da -analyze smg_axpy.bc
opt -da -analyze smg.bc
opt -da -analyze smg_relax.bc
opt -da -analyze smg_residual.bc
opt -da -analyze smg_setup.bc
opt -da -analyze smg_setup_interp.bc
opt -da -analyze smg_setup_rap.bc
opt -da -analyze smg_setup_restrict.bc
opt -da -analyze smg_solve.bc
opt -da -analyze struct_axpy.bc
opt -da -analyze struct_copy.bc
opt -da -analyze struct_grid.bc
opt -da -analyze struct_innerprod.bc
opt -da -analyze struct_io.bc
opt -da -analyze struct_matrix.bc
opt -da -analyze struct_matrix_mask.bc
opt -da -analyze struct_matvec.bc
opt -da -analyze struct_scale.bc
opt -da -analyze struct_stencil.bc
opt -da -analyze struct_vector.bc
opt -da -analyze threading.bc
opt -da -analyze timer.bc
opt -da -analyze timing.bc
